# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kyle Pollich
email: kpollich1@gmail.com
description: >
  Lancaster PA software engineer
baseurl: ""
url: "http://kpollich.github.io"
twitter_username: kylepollich
github_username:  kpollich

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highliter: rouge
